// Meter QR payload helpers.
//
// Canonical encoded format is "POW|<PN>|<METER>" — generated by both the
// per-meter MeterQRModal and the bulk qrStickerSheet. Field readers can
// resolve it offline against the cached batch.
//
// But physical meters in the field may carry stickers that pre-date this
// system (just the meter number printed bare, no PN), so parseMeterQR is
// intentionally tolerant of three forms:
//
//   1.  "POW|PN123|MTR456"   ← canonical
//   2.  "PN123|MTR456"       ← legacy two-token
//   3.  "MTR456"             ← bare meter number; caller must resolve the
//                              PN against the cached batch (returns
//                              meterOnly: true so the caller knows).

const PREFIX = "POW";

export function encodeMeterQR(pnNo, meterNumber) {
  return `${PREFIX}|${String(pnNo || "").toUpperCase().trim()}|${String(meterNumber || "").toUpperCase().trim()}`;
}

export function parseMeterQR(text) {
  if (!text) return null;
  const raw = String(text).trim();
  if (!raw) return null;

  const parts = raw.split("|").map((s) => s.trim()).filter(Boolean);
  if (parts.length === 0) return null;

  // 1) POW|PN|METER
  if (parts[0].toUpperCase() === PREFIX && parts.length >= 3) {
    return {
      pnNo: parts[1].toUpperCase(),
      meterNumber: parts[2].toUpperCase(),
      meterOnly: false,
    };
  }
  // 2) PN|METER
  if (parts.length >= 2) {
    return {
      pnNo: parts[0].toUpperCase(),
      meterNumber: parts[1].toUpperCase(),
      meterOnly: false,
    };
  }
  // 3) Bare meter number — single non-empty token, alphanumeric-ish.
  // Reject obvious garbage (URLs, sentences, etc.) so we don't try to
  // resolve "https://example.com" as a meter.
  const token = parts[0];
  if (/^[A-Z0-9_-]{3,32}$/i.test(token)) {
    return {
      pnNo: "",
      meterNumber: token.toUpperCase(),
      meterOnly: true,
    };
  }
  return null;
}
